### ISSUE TITLE
PageViewLog.user should be nullable

### ISSUE THREAD

**Issue by appetite-j** [Litiks/django-page_view_log#1]
Not all page views necessarily have a `user`. We currently have a hack in place to set `user_id` to `300` when nobody's logged in, but it would be better if we could set it to `null`

**Comment by aaronmader** [comment]
@appetite-j It looks like I'm not going to get to this today, but feel free to issue a pull request. 

The main thing is that some projects explicitely *want* to disregard any unauthenticated activity, so any change in this behaviour should be specifically opt-in. 

So we probably want to add support for a setting for like PAGE_VIEW_LOG_INCLUDES_ANONYMOUS, defaulting it to False.

**Comment by appetite-j** [comment]
Created pull request #2 to resolve this issue, and #3 and #4 for other housekeeping items.

**Comment by aaronmader** [comment]
Resolved with the merge of #2
